export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  // ── Account ───────────────────────────────────────────────────────────────
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  EMAIL_VERIFY_REQUESTED = 'EMAIL_VERIFY_REQUESTED',
  EMAIL_VERIFY_COMPLETED = 'EMAIL_VERIFY_COMPLETED',
  // ── Voting lifecycle ──────────────────────────────────────────────────────
  VOTING_CREATED = 'VOTING_CREATED',
  VOTING_OPENED = 'VOTING_OPENED',
  VOTING_CLOSED = 'VOTING_CLOSED',
  VOTING_FINALIZED = 'VOTING_FINALIZED',
  VOTING_DELETED = 'VOTING_DELETED',
  OPTION_ADDED = 'OPTION_ADDED',
  OPTION_UPDATED = 'OPTION_UPDATED',
  OPTION_REMOVED = 'OPTION_REMOVED',
  BALLOT_CAST = 'BALLOT_CAST',
  VOTING_RESULT_SEALED = 'VOTING_RESULT_SEALED',

  // ── Survey lifecycle ──────────────────────────────────────────────────────
  SURVEY_CREATED = 'SURVEY_CREATED',
  SURVEY_OPENED = 'SURVEY_OPENED',
  SURVEY_CLOSED = 'SURVEY_CLOSED',
  SURVEY_FINALIZED = 'SURVEY_FINALIZED',
  SURVEY_DELETED = 'SURVEY_DELETED',
  SURVEY_TOKEN_ISSUED = 'SURVEY_TOKEN_ISSUED',
  // SURVEY_BALLOT_CAST: userId MUST be null in the AuditLog row
  SURVEY_BALLOT_CAST = 'SURVEY_BALLOT_CAST',
  SURVEY_RESULT_SEALED = 'SURVEY_RESULT_SEALED',
  // ── Admin ─────────────────────────────────────────────────────────────────
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  GROUP_CREATED = 'GROUP_CREATED',
  GROUP_DELETED = 'GROUP_DELETED',
  MEMBER_ADDED = 'MEMBER_ADDED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
}
