export const TTL_ACTIONS = [
  "USER_LOGIN",
  "USER_LOGOUT",
  "USER_REGISTERED",
  "TOKEN_REFRESH",
  "PASSWORD_RESET_REQUESTED",
  "PASSWORD_RESET_COMPLETED",
  "EMAIL_VERIFY_REQUESTED",
  "EMAIL_VERIFY_COMPLETED",
];
