events {
    worker_connections 10240;
    multi_accept on;
}

http {
    upstream backend_servers {
        server backend:3001;
    }
    upstream frontend_servers {
        server frontend:3000;
    }
    log_format upstream_logging '[$time_local] IP: $remote_addr to: $upstream_addr | "$request" Status: $status';

    server {
        listen 80;
        
        access_log /var/log/nginx/access.log upstream_logging buffer=32k flush=5s;

        location /api/ {
            proxy_pass http://backend_servers/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /socket.io/ {
            proxy_pass http://backend_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://frontend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}